spring.application.name=socialfeed
##spring.data.mongodb.uri=YOUR_MONGODB_CONNECTION_STRING
spring.mongodb.database=socialfeed
spring.mongodb.uri=mongodb+srv://jalbizur_db_user:<Paxter123$>@jayoncluster.ez31axn.mongodb.net/?appName=JayonCluster